#!/usr/bin/env bash

cd ../images

cp skydivingformations_icon_512x512.png skydivingformations_icon_114x114.png
mogrify -resize 114x114 +gamma 0.0 skydivingformations_icon_114x114.png
cp skydivingformations_icon_512x512.png skydivingformations_icon_96x96.png
mogrify -resize 96x96 +gamma 0.0 skydivingformations_icon_96x96.png
cp skydivingformations_icon_512x512.png skydivingformations_icon_72x72.png
mogrify -resize 72x72 +gamma 0.0 skydivingformations_icon_72x72.png
cp skydivingformations_icon_512x512.png skydivingformations_icon_48x48.png
mogrify -resize 48x48 +gamma 0.0 skydivingformations_icon_48x48.png
cp skydivingformations_icon_512x512.png skydivingformations_icon_36x36.png
mogrify -resize 36x36 +gamma 0.0 skydivingformations_icon_36x36.png

cp skydivingformationslite_icon_512x512.png skydivingformationslite_icon_114x114.png
mogrify -resize 114x114 +gamma 0.0 skydivingformationslite_icon_114x114.png
cp skydivingformationslite_icon_512x512.png skydivingformationslite_icon_96x96.png
mogrify -resize 96x96 +gamma 0.0 skydivingformationslite_icon_96x96.png
cp skydivingformationslite_icon_512x512.png skydivingformationslite_icon_72x72.png
mogrify -resize 72x72 +gamma 0.0 skydivingformationslite_icon_72x72.png
cp skydivingformationslite_icon_512x512.png skydivingformationslite_icon_48x48.png
mogrify -resize 48x48 +gamma 0.0 skydivingformationslite_icon_48x48.png
cp skydivingformationslite_icon_512x512.png skydivingformationslite_icon_36x36.png
mogrify -resize 36x36 +gamma 0.0 skydivingformationslite_icon_36x36.png
